# Generated by Django 5.0.1 on 2024-01-09 16:36

import django.db.models.deletion
import taskapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='data',
            field=models.FileField(default=1, upload_to=taskapp.models.GenerateAttachmentPath()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='taskapp.task'),
        ),
    ]
