# Generated by Django 5.0.1 on 2024-01-11 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_attachment_data_alter_attachment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='taskapp.task'),
        ),
    ]
